import fs from "node:fs/promises";
import path from "node:path";
import { defineConfig, type Plugin } from "vite";
import { viteSingleFile } from "vite-plugin-singlefile";

const INPUT = process.env.INPUT;
if (!INPUT) {
  throw new Error("INPUT environment variable is not set");
}

const isDevelopment = process.env.NODE_ENV === "development";

/**
 * Writes the bundled single-file HTML into a TypeScript module that the server
 * imports, so the App resource never resolves a filesystem path at runtime.
 * stdio hosts (Claude Desktop) launch the server with cwd=/, where the old
 * process.cwd()-based lookup failed. Runs on every build, watch included.
 */
function inlineAppHtml(): Plugin {
  return {
    name: "webweaver:inline-app-html",
    closeBundle: async () => {
      const bundlePath = path.resolve("dist", "mcp-app.html");
      const html = await fs.readFile(bundlePath, "utf-8");

      // Guard against the historical regression where the unbundled source
      // HTML (a few KB, still pointing at the client entry) was served instead
      // of the ~330 KB single-file bundle.
      if (html.includes("/src/mcp-app.ts")) {
        throw new Error(
          `${bundlePath} still references the unbundled client entry — refusing to inline it.`,
        );
      }

      const outputPath = path.resolve("generated", "mcp-app-html.ts");
      await fs.mkdir(path.dirname(outputPath), { recursive: true });
      await fs.writeFile(
        outputPath,
        [
          "// Generated by vite.config.ts — do not edit.",
          "// Source: dist/mcp-app.html (Vite + vite-plugin-singlefile bundle).",
          "",
          `export const MCP_APP_HTML = ${JSON.stringify(html)};`,
          "",
        ].join("\n"),
      );
    },
  };
}

export default defineConfig({
  plugins: [viteSingleFile(), inlineAppHtml()],
  build: {
    sourcemap: isDevelopment ? "inline" : undefined,
    cssMinify: !isDevelopment,
    minify: !isDevelopment,
    rollupOptions: {
      input: INPUT,
    },
    outDir: "dist",
    emptyOutDir: false,
  },
});
